language: generic
# super user permissions
sudo: required
services: 
  - docker
# commands executed before running tests/deploy  
before_install:
  - docker build -t ktk001/docker-react-test -f Dockerfile.dev . # command to run docker similar to how you run the same in local. -t is to tag the generated image

script:
  - docker run -e CI=true ktk001/docker-react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-ap-south-1-727728554532"
  bucket_path: "docker-react-test"
  on:
    branch: master #deploy only when commit changes on master branch
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  