language: generic
# super user permissions
sudo: required
services: 
  - docker
# commands executed before running test/deploy  
before_install:
  - docker build -t ktk001/docker-react-test npm run test -f Dockerfile.dev .

script:
  - docker run -e CI=true ktk001/docker-react-test npm run test